language: python

jobs:
  include:
    - name: "py3.6 with PyQt5"
      python: 3.6
      before_install:
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash ./miniconda.sh -b -p ${HOME}/miniconda;
        export PATH=${HOME}/miniconda/bin:$PATH;
        conda install --yes python="3.6" pyqt="5.9";
        pip install pytest;

    - name: "py3.7 with PyQt5"
      python: 3.7
      before_install:
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash ./miniconda.sh -b -p ${HOME}/miniconda;
        export PATH=${HOME}/miniconda/bin:$PATH;
        conda install --yes python="3.7" pyqt="5.9";
        pip install pytest;

    - name: "py3.8 with PyQt5"
      python: 3.8
      before_install:
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash ./miniconda.sh -b -p ${HOME}/miniconda;
        export PATH=${HOME}/miniconda/bin:$PATH;
        conda install --yes python="3.8" pyqt="5.9";
        pip install pytest;
        
    - name: "py3.8 with PyQt5 - Win10"
      os: windows 
      language: shell
      before_install:
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe -O miniconda.sh;
        Miniconda3-latest-Windows-x86_64.exe;
        conda install --yes python="3.8" pyqt="5.9";
        pip install pytest;
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip install coveralls
  - pip install -e .[dev]

script:
  #- coverage run -p --source=src -m pytest
  #- PYTHONPATH=src pytest --cov src --cov-append
  - pytest --cov src --cov-append
    
after_success:
  - coverage combine
  #- coverage combine .coverage
  - coverage report -m
  - coveralls