language: python
env: QTLIB="None"

jobs:
  include:
    - name: "py36pyqt5"
      python: 3.6
      env: QTLIB="pyqt5"

    #- name: "py36pyqt6"
    #  python: 3.6
    #  env: QTLIB="pyqt6"

    - name: "py36pyside2"
      python: 3.6
      env: QTLIB="pyside2"

    #- name: "py36pyside6"
    #  python: 3.6
    #  env: QTLIB="pyside6"

    - name: "py39pyqt5"
      python: 3.9
      env: QTLIB="pyqt5"

    #- name: "py39pyqt6"
    #  python: 3.9
    #  env: QTLIB="pyqt6"

    - name: "py39pyside2"
      python: 3.9
      env: QTLIB="pyside2"

    #- name: "py39pyside6"
    #  python: 3.9
    #  env: QTLIB="pyside6"

    - name: "py39pyqt5_miniconda"
      python: 3.9
      before_install:
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash ./miniconda.sh -b -p ${HOME}/miniconda;
        export PATH=${HOME}/miniconda/bin:$PATH;
        conda install --yes python="3.9";
      env: QTLIB="pyqt5"

install:
  - pip install $QTLIB
  - pip install pytest-cov
  - pip install coveralls
  - pip install -e .

script:
  - pytest --cov src -s

after_success:
  - coverage report -m
  - coveralls